# Generated by Django 2.0.4 on 2018-10-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('number', models.CharField(max_length=30)),
                ('supply_date', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
