# Generated by Django 2.0.4 on 2018-10-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20181011_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
